language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack:
    secure: "bD4w0NoSqPHiTfLgNFw3CPK/Jg5IiUuPAJzsASmZNV2EiQMcf6s01LeRzWnFpMOU9o2ww6b8VjijBC5XetHx3JxFkotf08xngy7+ubdfsKw6/PXT0qU+G+rIJMemkHmwFopN1WoC1R2PPEFaufUOgi7/S5ZOEpIcrdTNo1DmoiuID6EMwbQx64tvyaPh7ojTIeu4kA0wQW/GPAWhqC1R/W7swaaBhzt+WXxeOmXvPtjC0Bt8sFZ3iC8e8a5ndLg7It/bTT1A+Cto1gUM/joznlVnRoTh34TgI9Hgc6KlxSPk4SMpneg+m0PP40bhC8ch8bOfkD89tg5RWuCmq6xr63b+bplFjKY9P+LEk+IILEdztSZEyLbcs4+5+IqqlNDocVpsRcdBC64A6cP6+AS4Ms5qGjA37wXUpHQbO5kvMo/FIGd5F/LqToMyMV0sH1TW/TyPwR3PLjgpvbGrZB+9qiJ4roJqaN9NUUpzjPOAnylpcbc04gMu/Pr4WmLi+lVpP0QU9ebLBjkUMCXOS7sA9udpFX6lHI61yvFQstPoTfGP9vCuVyL6ngkchGhFC/h6EdB+q27t/X6KunxP2i6LwKmfo1KYNw81RfPIWrJVLcbe1GX3WwJ6NnRdGbxeI4hZICZvJKN+3cINArQCetuTLtwVtWUSvLchMAysJV5w2pA="